### ISSUE TITLE
`Transmitter is None`

### ISSUE THREAD

**Issue by Crisfole** [TeamRemote/remote-sublime#12]
Installed the plugin and tried hosting and connecting. When connecting my partner and I both received the following:

```
diff
[Dummy-5-123145310703616 17:29:26]  Made diffs: [(1, 'H')]
[Dummy-5-123145310703616 17:29:26]  Made patch: [(1, 'H')]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 307, in on_modified_async
    callback.on_modified_async(v)
  File "remote in /Users/niall/Library/Application Support/Sublime Text 3/Installed Packages/RemoteCollab.sublime-package", line 23, in on_modified_async
  File "Session in /Users/niall/Library/Application Support/Sublime Text 3/Installed Packages/RemoteCollab.sublime-package", line 153, in send_diffs
AttributeError: 'NoneType' object has no attribute 'transmit'
```

It appears that somehow the `Session`'s `send_diffs` command is getting called before the `run` command finishes. I'm not sure how possible that is.

**Comment by hawkw** [comment]
Hmm, that definitely seems wrong.

This plugin hasn't been actively maintained for a while, but I may take a look at it.

**Comment by zedtux** [comment]
Facing the same issue here :(

**Comment by mgarbvs** [comment]
Any updates? Currently getting the same error on two machines, both running windows
